import type { Metadata } from "next";
import "./globals.css";
import { dir } from 'i18next'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params: { lng }
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string }
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body>
        {children}
      </body>
    </html>
  );
}
